const cfg=window.MBAPPE_SITE_CONFIG||{};
const ready=cfg.supabaseUrl&&cfg.supabaseAnonKey&&!cfg.supabaseUrl.includes('YOUR_PROJECT');
let db=null,items=[],last=0,busy=false;
const $=(s)=>document.querySelector(s);
const fallback=[{nickname:'战术复盘处',content:'经全场回看与情绪校准，我们确认：姆巴佩，我们对得起你。该传的爱已经传到位，该补的尊重已经补时绝平。',created_at:new Date().toISOString()},{nickname:'巴黎夜班档案员',content:'本人与所有同担在此郑重声明：我们从未亏欠，只是表达方式过于庄严，导致外界误以为这是一次道歉。',created_at:new Date(Date.now()-86400000).toISOString()}];
const templates={after:'经慎重复盘、逐帧核验、暂停三次深呼吸后，我方郑重宣布：姆巴佩，我们对得起你。所有欢呼均已按最高规格送达，所有偏爱均有据可查。',committee:'本委员会一致认为，所谓亏欠并不存在。我们向姆巴佩提交的不是道歉，而是一份长期、稳定、公开、可同步的支持证明。',romantic:'如果足球需要证词，那我愿意作证：姆巴佩，我们对得起你。每一次心动都合规，每一次尖叫都备案，每一次嗑到都算数。'};
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function msg(v){$('#form-message').textContent=v||''}
function render(){const today=new Date().toDateString();$('#total-count').textContent=items.length;$('#today-count').textContent=items.filter(x=>new Date(x.created_at).toDateString()===today).length;$('#wall-list').innerHTML=items.length?items.map(x=>'<article class="declaration-card"><blockquote>'+esc(x.content)+'</blockquote><div class="card-meta"><span>'+esc(x.nickname||'匿名签署人')+'</span><time>'+new Date(x.created_at).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})+'</time></div></article>').join(''):'<div class="empty-state">暂无公开宣言。第一份正式文件正在等待签署。</div>'}
async function load(){msg('正在核验公开宣言...');if(!db){items=fallback;render();msg('当前为预览数据。配置 Supabase 后会显示云端宣言。');return}const res=await db.from(cfg.tableName||'declarations').select('nickname,content,created_at').eq('is_hidden',false).order('created_at',{ascending:false}).limit(60);if(res.error){msg('云端读取失败：'+res.error.message);return}items=res.data||[];render();msg('')}
async function submit(e){e.preventDefault();if(busy)return;const content=$('#content').value.replace(/\s+/g,' ').trim().slice(0,280);const nickname=($('#nickname').value||'匿名签署人').replace(/\s+/g,' ').trim().slice(0,24);if(content.length<8){msg('宣言至少需要 8 个字。');return}if(Date.now()-last<8000){msg('稍后再签署。');return}if(!db){items=[{nickname:nickname,content:content,created_at:new Date().toISOString()}].concat(items);render();msg('已加入本页预览。配置 Supabase 后即可云端公示。');last=Date.now();return}busy=true;$('#submit-button').disabled=true;const res=await db.from(cfg.tableName||'declarations').insert({nickname:nickname,content:content}).select('nickname,content,created_at').single();busy=false;$('#submit-button').disabled=false;if(res.error){msg('签署失败：'+res.error.message);return}items=[res.data].concat(items);$('#content').value='';render();msg('宣言已公示。');last=Date.now()}
function init(){if(ready&&window.supabase)db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);$('#setup-notice').hidden=!!db;$('#content').value=templates.after;$('#char-count').textContent=$('#content').value.length+' / 280';document.querySelector('[data-template="after-review"]').onclick=()=>{$('#content').value=templates.after};document.querySelector('[data-template="committee"]').onclick=()=>{$('#content').value=templates.committee};document.querySelector('[data-template="romantic"]').onclick=()=>{$('#content').value=templates.romantic};$('#content').oninput=()=>{$('#char-count').textContent=$('#content').value.length+' / 280'};$('#refresh-button').onclick=load;$('#declaration-form').onsubmit=submit;load()}
init();
